apiVersion: batch/v1
kind: CronJob
metadata:
  name: build-cron
  namespace: NAMESPACE
  labels:
    app.kubernetes.part-of: NAME-website 
spec:
  schedule: "0/7 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 415
      template:
        metadata:
          namespace: NAME
          labels:
            app: build-cron
            app.kubernetes.part-of: NAME-website
        spec:
          containers:
          - image: domaindrivenarchitecture/c4k-website-build
            name: build-cron-container
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: BUILD_CPU_LIMIT
                memory: BUILD_MEMORY_LIMIT
            command: ["/entrypoint.sh"]
            envFrom:
            - configMapRef:
                name: build-configmap
            - secretRef:
                name: build-secret
            volumeMounts:
            - name: content-volume
              mountPath: /var/www/html/website
            - name: hash-state-volume
              mountPath: /var/hashfile.d
          volumes:
          - name: content-volume
            persistentVolumeClaim:
              claimName: content-volume
          - name: hash-state-volume
            persistentVolumeClaim:
              claimName: hash-state-volume
          restartPolicy: OnFailure
          