apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: content-volume
  namespace: NAME
  labels:
    app.kubernetes.part-of: NAME-website
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: WEBSITESTORAGESIZE
      