kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    app: nginx
  namespace: default
spec:    
  selector:
    app: nginx
  ports:
    - name: nginx-http
      port: 80             
    - name: nginx-https
      port: 443      
      