apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx volume to /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log                    
        - mountPath: /var/www/html/FQDN
          name: website-content-volume
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: nginx.conf
                path: conf.d/nginx.conf
              - key: FQDN.conf
                path: conf.d/nginx.conf
              - key: mime.types
                path: mime.d/mime.types # dig directory
        - name: log
          emptyDir: {}
        - name: website-content-volume
          persistentVolumeClaim:
            claimName: website-content-pvc

