kind: Service
apiVersion: v1
metadata:
  name: NAME
  namespace: default
  labels:
    app: NAME
    app.kubernetes.part-of: NAME
spec:    
  selector:
    app: NAME
  ports:
    - name: nginx-http
      port: 80               
      