kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    app: nginx
  namespace: default
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  selector:
    app: nginx
  ports:
    - port: 80       
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https