kind: Service
apiVersion: v1
metadata:
  name: NAME
  namespace: NAMESPACE
  labels:
    app: NAME
    app.kubernetes.part-of: NAME-website
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-http
      port: 80
