apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: NAME-build-cron
  labels:
    app.kubernetes.part-of: website # TODO: Review jem 2022/10/26: adjust name, add part of to all
spec:
  schedule: "0/7 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: domaindrivenarchitecture/c4k-website-build
            name: NAME-build-app
            imagePullPolicy: IfNotPresent
            command: ["/entrypoint.sh"]            
            envFrom:
            - secretRef:
                name: NAME-secret                   
            volumeMounts:
            - name: content-volume
              mountPath: /var/www/html/website
          volumes:
          - name: content-volume
            persistentVolumeClaim:
              claimName: NAME-content-volume
          restartPolicy: OnFailure
          