apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: NAME-build-cron
  labels:
    app.kubernetes.part-of: website # correct name?
spec:
  schedule: "1,7,14,21,28,35,42,49,54,59 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: domaindrivenarchitecture/c4k-website-build
            name: NAME-build-app
            imagePullPolicy: IfNotPresent
            command: ["/entrypoint.sh"]
            env:
            - name: HOSTADRESS
              value: FQDN
            envFrom:
            - secretRef:
                name: NAME-secret                   
            volumeMounts:
            - name: content-volume
              mountPath: /var/www/html/website
          volumes:
          - name: content-volume
            persistentVolumeClaim:
              claimName: NAME-content-volume
          restartPolicy: OnFailure