apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: website-data-pvc
  namespace: default
  labels:
    app: website
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:      
      storage: DATASTORAGESIZE
      